export interface Airport {
  name: string
  canonicalUrlToken: string
  code: string
  country: string
  countryCode: string
  airportGroupCode: string
  terminal: string | null
}

export const airports: Airport[] = [
  {
    name: "Tirana",
    canonicalUrlToken: "tirana",
    code: "TIA",
    country: "Albania",
    countryCode: "AL",
    airportGroupCode: "",
    terminal: "T1",
  },
  {
    name: "Graz",
    canonicalUrlToken: "graz",
    code: "GRZ",
    country: "Austria",
    countryCode: "AT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Innsbruck",
    canonicalUrlToken: "innsbruck",
    code: "INN",
    country: "Austria",
    countryCode: "AT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Klagenfurt",
    canonicalUrlToken: "klagenfurt",
    code: "KLU",
    country: "Austria",
    countryCode: "AT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Salzburg",
    canonicalUrlToken: "salzburg",
    code: "SZG",
    country: "Austria",
    countryCode: "AT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Vienna",
    canonicalUrlToken: "vienna",
    code: "VIE",
    country: "Austria",
    countryCode: "AT",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Brussels Intl",
    canonicalUrlToken: "brussels-intl",
    code: "BRU",
    country: "Belgium",
    countryCode: "BE",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Burgas",
    canonicalUrlToken: "burgas",
    code: "BOJ",
    country: "Bulgaria",
    countryCode: "BG",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Sofia",
    canonicalUrlToken: "sofia-intl",
    code: "SOF",
    country: "Bulgaria",
    countryCode: "BG",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Varna",
    canonicalUrlToken: "varna",
    code: "VAR",
    country: "Bulgaria",
    countryCode: "BG",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Dubrovnik",
    canonicalUrlToken: "dubrovnik",
    code: "DBV",
    country: "Croatia",
    countryCode: "HR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Rijeka",
    canonicalUrlToken: "rijeka",
    code: "RJK",
    country: "Croatia",
    countryCode: "HR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Pula",
    canonicalUrlToken: "pula",
    code: "PUY",
    country: "Croatia",
    countryCode: "HR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Split",
    canonicalUrlToken: "split",
    code: "SPU",
    country: "Croatia",
    countryCode: "HR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Zadar",
    canonicalUrlToken: "zadar",
    code: "ZAD",
    country: "Croatia",
    countryCode: "HR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Cyprus Larnaca",
    canonicalUrlToken: "cyprus-larnaca",
    code: "LCA",
    country: "Cyprus",
    countryCode: "CY",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Cyprus Paphos",
    canonicalUrlToken: "cyprus-paphos",
    code: "PFO",
    country: "Cyprus",
    countryCode: "CY",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Prague",
    canonicalUrlToken: "prague",
    code: "PRG",
    country: "Czech Republic",
    countryCode: "CZ",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Aarhus",
    canonicalUrlToken: "aarhus",
    code: "AAR",
    country: "Denmark",
    countryCode: "DK",
    airportGroupCode: "",
    terminal: "2",
  },
  {
    name: "Copenhagen",
    canonicalUrlToken: "copenhagen",
    code: "CPH",
    country: "Denmark",
    countryCode: "DK",
    airportGroupCode: "",
    terminal: "2",
  },
  {
    name: "Marsa Alam",
    canonicalUrlToken: "marsa-alam",
    code: "RMF",
    country: "Egypt",
    countryCode: "EG",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Hurghada",
    canonicalUrlToken: "hurghada",
    code: "HRG",
    country: "Egypt",
    countryCode: "EG",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Sharm El Sheikh",
    canonicalUrlToken: "sharm-el-sheikh",
    code: "SSH",
    country: "Egypt",
    countryCode: "EG",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Tallinn",
    canonicalUrlToken: "tallinn",
    code: "TLL",
    country: "Estonia",
    countryCode: "EE",
    airportGroupCode: "",
    terminal: "2",
  },
  {
    name: "Helsinki",
    canonicalUrlToken: "helsinki",
    code: "HEL",
    country: "Finland",
    countryCode: "FI",
    airportGroupCode: "",
    terminal: "2",
  },
  {
    name: "Kittila",
    canonicalUrlToken: "kittila",
    code: "KTT",
    country: "Finland",
    countryCode: "FI",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Rovaniemi",
    canonicalUrlToken: "rovaniemi",
    code: "RVN",
    country: "Finland",
    countryCode: "FI",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Biarritz",
    canonicalUrlToken: "biarritz",
    code: "BIQ",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: "Billi",
  },
  {
    name: "Bordeaux",
    canonicalUrlToken: "bordeaux",
    code: "BOD",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Brest Brittany",
    canonicalUrlToken: "brest-brittany",
    code: "BES",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Grenoble",
    canonicalUrlToken: "grenoble",
    code: "GNB",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "La Rochelle",
    canonicalUrlToken: "la-rochelle",
    code: "LRH",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Lille",
    canonicalUrlToken: "lille",
    code: "LIL",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: "2",
  },
  {
    name: "Rennes",
    canonicalUrlToken: "rennes",
    code: "RNS",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Limoges",
    canonicalUrlToken: "limoges",
    code: "LIG",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Lyon",
    canonicalUrlToken: "lyon",
    code: "LYS",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Marseille Provence",
    canonicalUrlToken: "marseille-provence",
    code: "MRS",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: "MP2",
  },
  {
    name: "Montpellier",
    canonicalUrlToken: "montpellier",
    code: "MPL",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Nantes",
    canonicalUrlToken: "nantes",
    code: "NTE",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Nice",
    canonicalUrlToken: "nice",
    code: "NCE",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: "2",
  },
  {
    name: "Pau Pyrénées",
    canonicalUrlToken: "pau",
    code: "PUF",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Tarbes-Lourdes–Pyrénées",
    canonicalUrlToken: "tarbes-lourdes–pyrenees",
    code: "LDE",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Toulon-Hyères",
    canonicalUrlToken: "toulon-hyeres",
    code: "TLN",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Toulouse",
    canonicalUrlToken: "toulouse",
    code: "TLS",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Ajaccio, Corsica",
    canonicalUrlToken: "ajaccio-corsica",
    code: "AJA",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "*CO",
    terminal: null,
  },
  {
    name: "Bastia, Corsica",
    canonicalUrlToken: "bastia-corsica",
    code: "BIA",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "*CO",
    terminal: null,
  },
  {
    name: "Calvi, Corsica",
    canonicalUrlToken: "calvi-corsica",
    code: "CLY",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "*CO",
    terminal: null,
  },
  {
    name: "Figari, Corsica",
    canonicalUrlToken: "figari-corsica",
    code: "FSC",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "*CO",
    terminal: null,
  },
  {
    name: "Paris Beauvais",
    canonicalUrlToken: "paris-beauvais",
    code: "BVA",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "*PA",
    terminal: "Ouest",
  },
  {
    name: "Paris Charles de Gaulle",
    canonicalUrlToken: "paris-charles-de-gaulle",
    code: "CDG",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "*PA",
    terminal: "2A",
  },
  {
    name: "Paris Orly",
    canonicalUrlToken: "paris-orly",
    code: "ORY",
    country: "France",
    countryCode: "FR",
    airportGroupCode: "*PA",
    terminal: "Ouest",
  },
  {
    name: "Berlin Brandenburg",
    canonicalUrlToken: "berlin-brandenburg",
    code: "BER",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Cologne Bonn",
    canonicalUrlToken: "cologne-bonn",
    code: "CGN",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Dortmund",
    canonicalUrlToken: "dortmund",
    code: "DTM",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Dresden",
    canonicalUrlToken: "dresden",
    code: "DRS",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Frankfurt International",
    canonicalUrlToken: "frankfurt",
    code: "FRA",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Dusseldorf",
    canonicalUrlToken: "dusseldorf",
    code: "DUS",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Hamburg",
    canonicalUrlToken: "hamburg",
    code: "HAM",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Munich",
    canonicalUrlToken: "munich",
    code: "MUC",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: "2",
  },
  {
    name: "Friedrichshafen",
    canonicalUrlToken: "friedrichshafen",
    code: "FDH",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Stuttgart",
    canonicalUrlToken: "stuttgart",
    code: "STR",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Sylt",
    canonicalUrlToken: "sylt",
    code: "GWT",
    country: "Germany",
    countryCode: "DE",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Gibraltar",
    canonicalUrlToken: "gibraltar",
    code: "GIB",
    country: "Gibraltar",
    countryCode: "Gibraltar",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Athens",
    canonicalUrlToken: "athens",
    code: "ATH",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Corfu",
    canonicalUrlToken: "corfu",
    code: "CFU",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Kalamata",
    canonicalUrlToken: "kalamata",
    code: "KLX",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Kefalonia",
    canonicalUrlToken: "kefalonia",
    code: "EFL",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Kos",
    canonicalUrlToken: "kos",
    code: "KGS",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Mykonos",
    canonicalUrlToken: "mykonos",
    code: "JMK",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Preveza",
    canonicalUrlToken: "preveza",
    code: "PVK",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Rhodes",
    canonicalUrlToken: "rhodes",
    code: "RHO",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Santorini",
    canonicalUrlToken: "santorini",
    code: "JTR",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Skiathos",
    canonicalUrlToken: "skiathos",
    code: "JSI",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Thessaloniki",
    canonicalUrlToken: "thessaloniki",
    code: "SKG",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Volos",
    canonicalUrlToken: "volos",
    code: "VOL",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Zante Zakynthos",
    canonicalUrlToken: "zante-zakynthos",
    code: "ZTH",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Crete Chania",
    canonicalUrlToken: "crete-chania",
    code: "CHQ",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "*CR",
    terminal: null,
  },
  {
    name: "Crete Heraklion",
    canonicalUrlToken: "crete-heraklion",
    code: "HER",
    country: "Greece",
    countryCode: "GR",
    airportGroupCode: "*CR",
    terminal: null,
  },
  {
    name: "Budapest",
    canonicalUrlToken: "budapest",
    code: "BUD",
    country: "Hungary",
    countryCode: "HU",
    airportGroupCode: "",
    terminal: "2A",
  },
  {
    name: "Reykjavik Keflavik",
    canonicalUrlToken: "reykjavik-keflavik",
    code: "KEF",
    country: "Iceland",
    countryCode: "IS",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Tel Aviv",
    canonicalUrlToken: "tel-aviv",
    code: "TLV",
    country: "Israel",
    countryCode: "IL",
    airportGroupCode: "",
    terminal: "3",
  },
  {
    name: "Rome Fiumicino",
    canonicalUrlToken: "rome-fiumicino",
    code: "FCO",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Ancona",
    canonicalUrlToken: "ancona",
    code: "AOI",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Bari",
    canonicalUrlToken: "bari",
    code: "BRI",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Genoa",
    canonicalUrlToken: "genoa",
    code: "GOA",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Bologna",
    canonicalUrlToken: "bologna",
    code: "BLQ",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Brindisi",
    canonicalUrlToken: "brindisi",
    code: "BDS",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Lamezia",
    canonicalUrlToken: "lamezia",
    code: "SUF",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Naples",
    canonicalUrlToken: "naples",
    code: "NAP",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Pisa (Tuscany)",
    canonicalUrlToken: "pisa-tuscany",
    code: "PSA",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Turin",
    canonicalUrlToken: "turin",
    code: "TRN",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Venice Marco Polo",
    canonicalUrlToken: "venice-marco-polo",
    code: "VCE",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Verona",
    canonicalUrlToken: "verona",
    code: "VRN",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Sardinia Alghero",
    canonicalUrlToken: "sardinia-alghero",
    code: "AHO",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "*SD",
    terminal: null,
  },
  {
    name: "Sardinia Cagliari",
    canonicalUrlToken: "sardinia-cagliari",
    code: "CAG",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "*SD",
    terminal: null,
  },
  {
    name: "Sardinia Olbia",
    canonicalUrlToken: "sardinia-olbia",
    code: "OLB",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "*SD",
    terminal: null,
  },
  {
    name: "Milan Bergamo",
    canonicalUrlToken: "milan-bergamo",
    code: "BGY",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "*MI",
    terminal: "1",
  },
  {
    name: "Milan Malpensa",
    canonicalUrlToken: "milan-malpensa",
    code: "MXP",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "*MI",
    terminal: "1",
  },
  {
    name: "Milan Linate",
    canonicalUrlToken: "milan-linate",
    code: "LIN",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "*MI",
    terminal: null,
  },
  {
    name: "Lampedusa",
    canonicalUrlToken: "lampedusa",
    code: "LMP",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "*SY",
    terminal: null,
  },
  {
    name: "Sicily Catania",
    canonicalUrlToken: "catania-sicily",
    code: "CTA",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "*SY",
    terminal: "A",
  },
  {
    name: "Sicily Comiso",
    canonicalUrlToken: "comiso-sicilia",
    code: "CIY",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "*SY",
    terminal: null,
  },
  {
    name: "Sicily Palermo",
    canonicalUrlToken: "palermo-sicily",
    code: "PMO",
    country: "Italy",
    countryCode: "IT",
    airportGroupCode: "*SY",
    terminal: null,
  },
  {
    name: "Aqaba",
    canonicalUrlToken: "aqaba",
    code: "AQJ",
    country: "Jordan",
    countryCode: "JO",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Pristina",
    canonicalUrlToken: "pristina",
    code: "PRN",
    country: "Kosovo",
    countryCode: "XK",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Luxembourg",
    canonicalUrlToken: "luxembourg",
    code: "LUX",
    country: "Luxembourg",
    countryCode: "LU",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Malta",
    canonicalUrlToken: "malta",
    code: "MLA",
    country: "Malta",
    countryCode: "MT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Agadir",
    canonicalUrlToken: "agadir",
    code: "AGA",
    country: "Morocco",
    countryCode: "MA",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Essaouira",
    canonicalUrlToken: "essaouira",
    code: "ESU",
    country: "Morocco",
    countryCode: "MA",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Marrakech",
    canonicalUrlToken: "marrakech",
    code: "RAK",
    country: "Morocco",
    countryCode: "MA",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Tangier",
    canonicalUrlToken: "tangier",
    code: "TNG",
    country: "Morocco",
    countryCode: "MA",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Tivat",
    canonicalUrlToken: "tivat",
    code: "TIV",
    country: "Montenegro",
    countryCode: "ME",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Amsterdam",
    canonicalUrlToken: "amsterdam",
    code: "AMS",
    country: "Netherlands",
    countryCode: "NL",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Skopje",
    canonicalUrlToken: "skopje-international-airport",
    code: "SKP",
    country: "North Macedonia",
    countryCode: "MK",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Oslo",
    canonicalUrlToken: "oslo",
    code: "OSL",
    country: "Norway",
    countryCode: "NO",
    airportGroupCode: "",
    terminal: "2",
  },
  {
    name: "Gdansk",
    canonicalUrlToken: "gdansk",
    code: "GDN",
    country: "Poland",
    countryCode: "PL",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Krakow",
    canonicalUrlToken: "krakow",
    code: "KRK",
    country: "Poland",
    countryCode: "PL",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Lublin",
    canonicalUrlToken: "lublin",
    code: "LUZ",
    country: "Poland",
    countryCode: "PL",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Warsaw",
    canonicalUrlToken: "warsaw",
    code: "WAW",
    country: "Poland",
    countryCode: "PL",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Faro",
    canonicalUrlToken: "faro",
    code: "FAO",
    country: "Portugal",
    countryCode: "PT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Lisbon",
    canonicalUrlToken: "lisbon",
    code: "LIS",
    country: "Portugal",
    countryCode: "PT",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Madeira Funchal",
    canonicalUrlToken: "madeira-funchal",
    code: "FNC",
    country: "Portugal",
    countryCode: "PT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Porto",
    canonicalUrlToken: "porto",
    code: "OPO",
    country: "Portugal",
    countryCode: "PT",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Porto Santo",
    canonicalUrlToken: "porto-santo",
    code: "PXO",
    country: "Portugal",
    countryCode: "PT",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Bucharest (Otopeni)",
    canonicalUrlToken: "bucharest-otopeni",
    code: "OTP",
    country: "Romania",
    countryCode: "RO",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Belgrade",
    canonicalUrlToken: "belgrade",
    code: "BEG",
    country: "Serbia",
    countryCode: "RS",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Ljubljana",
    canonicalUrlToken: "ljubljana",
    code: "LJU",
    country: "Slovenia",
    countryCode: "SI",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Jerez de la Frontera",
    canonicalUrlToken: "jerez-de-la-frontera",
    code: "XRY",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Alicante",
    canonicalUrlToken: "alicante",
    code: "ALC",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Almeria",
    canonicalUrlToken: "almeria",
    code: "LEI",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Barcelona",
    canonicalUrlToken: "barcelona",
    code: "BCN",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Bilbao",
    canonicalUrlToken: "bilbao",
    code: "BIO",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Ibiza",
    canonicalUrlToken: "ibiza",
    code: "IBZ",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "La Coruña",
    canonicalUrlToken: "la-coruna",
    code: "LCG",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Madrid",
    canonicalUrlToken: "madrid",
    code: "MAD",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "4",
  },
  {
    name: "Majorca Palma",
    canonicalUrlToken: "majorca-palma",
    code: "PMI",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Granada",
    canonicalUrlToken: "granada",
    code: "GRX",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Malaga",
    canonicalUrlToken: "malaga",
    code: "AGP",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "3",
  },
  {
    name: "Menorca Mahon",
    canonicalUrlToken: "menorca-mahon",
    code: "MAH",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Murcia Intl",
    canonicalUrlToken: "murcia-intl",
    code: "RMU",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Reus",
    canonicalUrlToken: "reus",
    code: "REU",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Santiago de Compostela",
    canonicalUrlToken: "santiago-de-compostela",
    code: "SCQ",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Seville",
    canonicalUrlToken: "seville",
    code: "SVQ",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Valencia",
    canonicalUrlToken: "valencia",
    code: "VLC",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Santa Cruz de la Palma",
    canonicalUrlToken: "la-palma",
    code: "SPC",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "*CN",
    terminal: null,
  },
  {
    name: "Fuerteventura",
    canonicalUrlToken: "fuerteventura",
    code: "FUE",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "*CN",
    terminal: null,
  },
  {
    name: "Gran Canaria",
    canonicalUrlToken: "gran-canaria-las-palmas",
    code: "LPA",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "*CN",
    terminal: null,
  },
  {
    name: "Lanzarote",
    canonicalUrlToken: "lanzarote-arrecife",
    code: "ACE",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "*CN",
    terminal: null,
  },
  {
    name: "Tenerife South",
    canonicalUrlToken: "tenerife-south",
    code: "TFS",
    country: "Spain",
    countryCode: "ES",
    airportGroupCode: "*CN",
    terminal: "1",
  },
  {
    name: "Are Ostersund",
    canonicalUrlToken: "are-ostersund",
    code: "OSD",
    country: "Sweden",
    countryCode: "SE",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Gothenburg",
    canonicalUrlToken: "gothenburg",
    code: "GOT",
    country: "Sweden",
    countryCode: "SE",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Stockholm Arlanda",
    canonicalUrlToken: "stockholm-arlanda",
    code: "ARN",
    country: "Sweden",
    countryCode: "SE",
    airportGroupCode: "",
    terminal: "5",
  },
  {
    name: "Basel",
    canonicalUrlToken: "basel-mulhouse-freiburg",
    code: "BSL",
    country: "Switzerland",
    countryCode: "CH",
    airportGroupCode: "",
    terminal: "A",
  },
  {
    name: "Geneva",
    canonicalUrlToken: "geneva",
    code: "GVA",
    country: "Switzerland",
    countryCode: "CH",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Zurich",
    canonicalUrlToken: "zurich",
    code: "ZRH",
    country: "Switzerland",
    countryCode: "CH",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Enfidha - Hammamet",
    canonicalUrlToken: "enfidha-hammamet",
    code: "NBE",
    country: "Tunisia",
    countryCode: "TN",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Antalya",
    canonicalUrlToken: "antalya",
    code: "AYT",
    country: "Turkey",
    countryCode: "TR",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Bodrum",
    canonicalUrlToken: "bodrum",
    code: "BJV",
    country: "Turkey",
    countryCode: "TR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Dalaman",
    canonicalUrlToken: "dalaman",
    code: "DLM",
    country: "Turkey",
    countryCode: "TR",
    airportGroupCode: "",
    terminal: "D",
  },
  {
    name: "Istanbul",
    canonicalUrlToken: "​​​​​​​​​​​​​​​Istanbul-Airport",
    code: "IST",
    country: "Turkey",
    countryCode: "TR",
    airportGroupCode: "",
    terminal: "I",
  },
  {
    name: "Izmir",
    canonicalUrlToken: "izmir",
    code: "ADB",
    country: "Turkey",
    countryCode: "TR",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Aberdeen",
    canonicalUrlToken: "aberdeen",
    code: "ABZ",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Birmingham",
    canonicalUrlToken: "birmingham",
    code: "BHX",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Bournemouth",
    canonicalUrlToken: "bournemouth",
    code: "BOH",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Bristol",
    canonicalUrlToken: "bristol",
    code: "BRS",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "East Midlands",
    canonicalUrlToken: "east-midlands",
    code: "EMA",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Inverness",
    canonicalUrlToken: "inverness",
    code: "INV",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Isle of Man",
    canonicalUrlToken: "isle-of-man",
    code: "IOM",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Jersey",
    canonicalUrlToken: "jersey",
    code: "JER",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Leeds Bradford",
    canonicalUrlToken: "leeds-bradford",
    code: "LBA",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Liverpool",
    canonicalUrlToken: "liverpool",
    code: "LPL",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Manchester",
    canonicalUrlToken: "manchester",
    code: "MAN",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Newcastle",
    canonicalUrlToken: "newcastle",
    code: "NCL",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: "1",
  },
  {
    name: "Newquay",
    canonicalUrlToken: "newquay",
    code: "NQY",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Southampton",
    canonicalUrlToken: "southampton",
    code: "SOU",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "",
    terminal: null,
  },
  {
    name: "Edinburgh",
    canonicalUrlToken: "edinburgh",
    code: "EDI",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "*SC",
    terminal: "1",
  },
  {
    name: "Glasgow",
    canonicalUrlToken: "glasgow",
    code: "GLA",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "*SC",
    terminal: "1",
  },
  {
    name: "Belfast City (George Best)",
    canonicalUrlToken: "belfast-city-george-best",
    code: "BHD",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "*BE",
    terminal: "1",
  },
  {
    name: "Belfast Intl",
    canonicalUrlToken: "belfast-intl",
    code: "BFS",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "*BE",
    terminal: "2",
  },
  {
    name: "London Gatwick",
    canonicalUrlToken: "london-gatwick",
    code: "LGW",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "*LO",
    terminal: "S",
  },
  {
    name: "London Luton",
    canonicalUrlToken: "london-luton",
    code: "LTN",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "*LO",
    terminal: "1",
  },
  {
    name: "London Southend",
    canonicalUrlToken: "london-southend",
    code: "SEN",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "*LO",
    terminal: null,
  },
  {
    name: "London Stansted",
    canonicalUrlToken: "london-stansted",
    code: "STN",
    country: "United Kingdom",
    countryCode: "GB",
    airportGroupCode: "*LO",
    terminal: null,
  },
]
