const passengers = [
  {
    uid: "amRn60V" as const,
    id: "0***1005 (P)" as const,
    gender: "male" as const,
    title: "Dr." as const,
    firstName: "Pieter" as const,
    lastName: "Peeters" as const,
    type: "Adult" as const,
    selectedSeat: "1A" as const,
    selectedSeatType: "Standard" as const,
    hasSmallCabinBag: true as const,
    hasLargeCabinBag: false as const,
  },
  {
    uid: "JLBeLmW" as const,
    id: "4***0767 (P)" as const,
    gender: "female" as const,
    title: "Drs." as const,
    firstName: "Ruby" as const,
    lastName: "Postma" as const,
    type: "Adult" as const,
    selectedSeat: "1A" as const,
    selectedSeatType: "Standard" as const,
    hasSmallCabinBag: true as const,
    hasLargeCabinBag: false as const,
  },
  {
    uid: "r4UBuek" as const,
    id: "7***2911 (P)" as const,
    gender: "female" as const,
    title: "Drs." as const,
    firstName: "Aya" as const,
    lastName: "Verbeek" as const,
    type: "Adult" as const,
    selectedSeat: "1A" as const,
    selectedSeatType: "Standard" as const,
    hasSmallCabinBag: true as const,
    hasLargeCabinBag: false as const,
  },
  {
    uid: "RwMCdJt" as const,
    id: "6***1203 (P)" as const,
    gender: "male" as const,
    title: "Dr." as const,
    firstName: "Willem" as const,
    lastName: "Verhoeven" as const,
    type: "Adult" as const,
    selectedSeat: "1A" as const,
    selectedSeatType: "Standard" as const,
    hasSmallCabinBag: true as const,
    hasLargeCabinBag: false as const,
  },
  {
    uid: "uicQMW3" as const,
    id: "1***2987 (P)" as const,
    gender: "male" as const,
    title: "Dhr." as const,
    firstName: "Lucas" as const,
    lastName: "Wagenaar" as const,
    type: "Adult" as const,
    selectedSeat: "1A" as const,
    selectedSeatType: "Standard" as const,
    hasSmallCabinBag: true as const,
    hasLargeCabinBag: false as const,
  },
  {
    uid: "gPUgq6B" as const,
    id: "2***2993 (P)" as const,
    gender: "female" as const,
    title: "Bsc" as const,
    firstName: "Fien" as const,
    lastName: "Willems" as const,
    type: "Adult" as const,
    selectedSeat: "1A" as const,
    selectedSeatType: "Standard" as const,
    hasSmallCabinBag: true as const,
    hasLargeCabinBag: false as const,
    infant: {
      uid: "rzqqLcX" as const,
      id: "7***S3FZ (I)" as const,
      gender: "male" as const,
      title: "Drs." as const,
      firstName: "Youp" as const,
      lastName: "Willems" as const,
      type: "Infant" as const,
      selectedSeat: "1A" as const,
      selectedSeatType: "Standard" as const,
      hasSmallCabinBag: false as const,
      hasLargeCabinBag: false as const,
    },
  },
]

const extras = {
  hasSmallCabinBag: true as const,
  hasLargeCabinBag: false as const,
  holdBags: [
    { name: "Hold Bag" as const, weight: 15, amount: 0 },
    { name: "Hold Bag" as const, weight: 23, amount: 0 },
    { name: "Hold Bag" as const, weight: 26, amount: 0 },
    { name: "Hold Bag" as const, weight: 29, amount: 0 },
    { name: "Hold Bag" as const, weight: 32, amount: 0 },
  ],
  sportsEquipment: [
    { name: "Bicycle" as const, amount: 0 },
    { name: "Canoe" as const, amount: 0 },
    { name: "Sporting firearm" as const, amount: 0 },
    { name: "Golf bag" as const, amount: 0 },
    { name: "Hang glider" as const, amount: 0 },
    { name: "Skis and/or boots" as const, amount: 0 },
    { name: "Snowboard" as const, amount: 0 },
    { name: "Windsurfing board" as const, amount: 0 },
  ],
  hasSpeedyBoarding: false as const,
  hasEasyJetPlusBagDrop: true as const,
  hasFastTrackSecurity: false as const,
  hasMealDeal: true as const,
}

export const booking = {
  hasEasyJetPlus: true as const,
  bookingLabel: "Standby Fare" as const,
  bookingFareType: "Standard" as const,
  bookingBundle: "Essentials" as const,
  passengers,
  flights: [
    {
      uid: "VOBJjEx" as const,
      departureDate: new Date("2023-10-03T16:49:05.231Z"),
      departureAirport: {
        name: "Luxembourg" as const,
        canonicalUrlToken: "luxembourg" as const,
        code: "LUX" as const,
        country: "Luxembourg" as const,
        countryCode: "LU" as const,
        airportGroupCode: "" as const,
        terminal: "A" as const,
      },
      arrivalDate: new Date("2023-10-04T02:49:05.231Z"),
      arrivalAirport: {
        name: "Cologne Bonn" as const,
        canonicalUrlToken: "cologne-bonn" as const,
        code: "CGN" as const,
        country: "Germany" as const,
        countryCode: "DE" as const,
        airportGroupCode: "" as const,
        terminal: "1" as const,
      },
      number: "EZY0025" as const,
      reservationNumber: "TJ9J0RI" as const,
      checkInSequenceNumber: "S300" as const,
      customerEntitlementsCode: "S2" as const,
      passengers,
      extras,
    },
    {
      uid: "66iqrHa" as const,
      departureDate: new Date("2023-10-05T02:49:05.231Z"),
      departureAirport: {
        name: "Gran Canaria" as const,
        canonicalUrlToken: "gran-canaria-las-palmas" as const,
        code: "LPA" as const,
        country: "Spain" as const,
        countryCode: "ES" as const,
        airportGroupCode: "*CN" as const,
        terminal: null,
      },
      arrivalDate: new Date("2023-10-05T06:04:05.231Z"),
      arrivalAirport: {
        name: "Belgrade" as const,
        canonicalUrlToken: "belgrade" as const,
        code: "BEG" as const,
        country: "Serbia" as const,
        countryCode: "RS" as const,
        airportGroupCode: "" as const,
        terminal: "1" as const,
      },
      number: "EZY0009" as const,
      reservationNumber: "WRWLWII" as const,
      checkInSequenceNumber: "S900" as const,
      customerEntitlementsCode: "S2" as const,
      passengers,
      extras,
    },
  ],
  language: {
    value: "Nederlands" as const,
    locale: "nl_NL" as const,
    flag: "netherlands" as const,
  },
}
